// Generated by CoffeeScript 1.10.0
(function() {
  var child, children, ckey, log, testfun;

  log = function(str) {
    return console.log(str);
  };

  log("Hello CoffeeScript");

  testfun = function(param) {
    var i, result, results;
    results = [];
    for (result = i = 1; i <= 10; result = ++i) {
      if (result !== param) {
        results.push(log(result));
      }
    }
    return results;
  };

  testfun(2);

  children = {
    name: 'child',
    age: 20,
    type: 'singing'
  };

  for (child in children) {
    ckey = children[child];
    log(child + " " + ckey);
  }

}).call(this);
